version: '3'
services:
  postgres:
    image: postgres:16
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  # python-script:
  #   build: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     - POSTGRES_DB=mydatabase
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
  #   command: python query_database.py

  flask-app:
    build:
      context: ./web_data
    environment:
      - FLASK_URL=http://localhost:5000
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres  
      - POSTGRES_PORT=5432
    volumes:
      - ./web_data:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  pgdata:

